### ISSUE TITLE
Moving away and then selecting Shaman as your deck crashes to desktop

### ISSUE THREAD

**Issue by Artanixuk** [JulianEberius/track-o-bot-ios#10]
iPhone 6S again (latest iOS). Happens 100% of the time.
1. Open app - Default "your deck" seems to be Shaman - Other Shaman
2. Move selection away to any other class and deck.
3. Move back to Shaman
4. Crashes to desktop

Seems to happen when selecting Opponent deck too.

**Comment by JulianEberius** [comment]
Thanks for your report. Yes the whole view is completely unstable, I don't know why I didn't notice that myself. I've reverted testing to 1.0.0 (which was much more stable, even with the rotation crash) and will look into this, as soon as I have some free time.

**Comment by JulianEberius** [comment]
Fixed in current Beta (1.0.2 Build 2).
