### ISSUE TITLE
Selecting last deck for a class makes it get recorded as "Other"

### ISSUE THREAD

**Issue by ddlevine** [JulianEberius/track-o-bot-ios#12]
When I select the last deck in the list for a class, it gets recorded as "Other." 
Example: Record game against Taunt Warrior. Game gets recorded as being against Other Warrior.

The list of decks impacted by this bug are as follows:

Taunt Warrior
Midrange Shaman
Miracle Rogue
Aggro Paladin
Face Hunter
Jade Druid
Hand Warlock
Freeze Mage
Combo Priest

**Comment by ddlevine** [comment]
This isn't always occurring. It's sparadic. I can't seem to find a regular pattern.

**Comment by JulianEberius** [comment]
Thanks a lot for you report. This is fixed in the current build, which I just uploaded to the AppStore. The update should roll out in a couple of days (depends on Apple Review).

Thanks again,
Julian

**Comment by ddlevine** [comment]
Awesome! Thank you so much!
