### ISSUE TITLE
No longer available on the App Store

### ISSUE THREAD

**Issue by ulirg** [JulianEberius/track-o-bot-ios#13]
Upgraded from an iPhone 8 to the iPhone Xs and now I can't download Track-o-Botty on the new phone as the App Store says this app is no longer available. Hopefully the app just needs a recompile against the new SDK?

**Comment by JulianEberius** [comment]
Sorry, this is true. I'm not an iOS developer by trade, and I currently develop no other iOS or Mac applications. I simply didn't pay the yearly 99$ for the Apple Developer Program , so they removed the app from the store. 

The good news is that the app is open source, so if you have a Mac, or know someone with a Mac, you can install the app for free by downloading Xcode, opening the project, connecting your device, and running the project.

**Comment by ulirg** [comment]
That's a shame because the app still works great. Would you be willing to have someone else handle the App Store upload process? I'm sure there's plenty of iOS developers playing HS. I might put out a call for help on Reddit, if you don't mind?

**Comment by ulirg** [comment]
Followed [this guide](http://osxdaily.com/2016/01/12/howto-sideload-apps-iphone-ipad-xcode/) for side loading and was able to install the app onto my new phone.
