### ISSUE TITLE
Allow the user to select specific decks in addition to heroes

### ISSUE THREAD

**Issue by JulianEberius** [JulianEberius/track-o-bot-ios#4]
The user-defined decks are currently not available via API. I have opened an issue at https://github.com/stevschmid/trackobot.com/issues/26 and may also make a pull request there.

**Comment by bl4ck0r** [comment]
+1 would be amazing to track all matchups correct and efficient! tier1 !

**Comment by JulianEberius** [comment]
The app allows to select decks in the UI now, but the correct trackobot.com API is, sadly, not yet in place. The app currently uses a workaround that only provides the deck names, but not to which hero they belong. So for testing, currently all decks can be selected for all heroes.

**Comment by JulianEberius** [comment]
Current beta version supports selecting decks
